# -*- coding: utf-8 -*-
"""JO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17j2HRhbYW9aW-udZvenPnuZdS8yEbWqq
"""

import pandas as pd
import plotly.express as px

df = pd.read_csv('projet_datavis2024_jo.csv')

fig = px.line(df, x = 'year', y = 'athletes', title='Nb athletes a travers des JO')
#fig = px.pie(df, values='age', names='film_titre', title="Films CEN")
fig.show()